### ISSUE TITLE
Add loader

### ISSUE THREAD

**Issue by e-coders** [AjitVerma15/Interactive-Portfolio#3]
As in your README's For the future section, you want to add a loader. I can help you in that. Here's how:
Create a JS File called loader or your choice, link it at bottom of the body tag under body tag and also add 'defer=defer' in the script tag which you will use to link the JS File.
In loader.js, type the given code. Replace the comment by the code to be executed after the page is loaded.
```javascript
document.body.addEventListener("load", (e) => {
    // code to be executed after the page is loaded
})
```
If you confused where the script tag and what tag to be added, see the syntax here:
```html
<html>
<head>
<!-- Your Head Tag Code -->
</head>
<body>
<!-- Your Body Tag Code -->

<!-- The below is the code to be added -->
<script defer="defer" src="loader.js"></script>
</body>
</html>
```

**Comment by AjitVerma15** [comment]
Thank you for your valuable knowledge.

**Comment by e-coders** [comment]
Your welcome!

**Comment by e-coders** [comment]
If you want to connect to more great developers with me, share me your email id. My is code.with.aasheesh@gmail.com and your? If you give it so please keep checking your Inbox as I will connect you to others and also send a first email message. Please share a google mail to connect as for ease.

**Comment by AjitVerma15** [comment]
My email id is ajitverma2101@gmail.com, excited to connect with great developers.

**Comment by e-coders** [comment]
OK! My is code.with.aasheesh@gmail.com! I'll send you a mail, then will add you to my friend's Google Chat group! I'm also excited to connect to you!!!

**Comment by e-coders** [comment]
(Name: Aasheesh)

**Comment by e-coders** [comment]
I've sent a mail. And also added to my friend's tallking place, where we talk about many things also related to programming!

**Comment by e-coders** [comment]
Join: Programmers Palace
